services:
  - type: web_service
    name: product-recommendation
    env: docker
    plan: free
    dockerComposeFilePath: ./docker-compose.yml
    dockerComposeService: java-api
    region: oregon
    autoDeploy: true
